"""Cadence database layer: Supabase PostgreSQL, with SQLite for local tests."""

import os
import json
import sqlite3
from pathlib import Path
from uuid import uuid4
from datetime import datetime, date
from contextlib import contextmanager

import psycopg
from psycopg.rows import dict_row
from dotenv import load_dotenv

load_dotenv(Path(__file__).with_name(".env"))
DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
# Tests explicitly supply a temporary SQLite path. Normal startup requires Supabase.
DB_PATH = None
INTEGRITY_ERRORS = (sqlite3.IntegrityError, psycopg.IntegrityError)


class _SQLiteConnection:
    """Keep application SQL in PostgreSQL's parameter style for both backends."""

    def __init__(self, connection):
        self.connection = connection

    def execute(self, query, params=()):
        return self.connection.execute(query.replace("%s", "?"), params)


@contextmanager
def get_conn():
    if DATABASE_URL:
        if not DATABASE_URL.startswith(("postgresql://", "postgres://")):
            raise ValueError("DATABASE_URL must be a PostgreSQL connection URL")
        with psycopg.connect(
            DATABASE_URL, row_factory=dict_row, connect_timeout=10,
            sslmode="require", prepare_threshold=None,
        ) as conn:
            yield conn
        return

    if DB_PATH is None:
        raise ValueError("Set DATABASE_URL in backend/.env to your Supabase PostgreSQL URL")
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        yield _SQLiteConnection(conn)
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def _column_names(conn, table):
    if isinstance(conn, _SQLiteConnection):
        return {row["name"] for row in conn.execute(f"PRAGMA table_info({table})")}
    return {row["column_name"] for row in conn.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema=current_schema() AND table_name=%s", (table,),
    )}


def _lock_user_writes(conn):
    # Serialize the case-insensitive email check with concurrent user writes.
    if isinstance(conn, _SQLiteConnection):
        conn.execute("BEGIN IMMEDIATE")
    else:
        conn.execute("LOCK TABLE users IN SHARE ROW EXCLUSIVE MODE")


def init_db():
    with get_conn() as conn:
        initialize_schema(conn)


def initialize_schema(conn):
    """Create and upgrade the schema within the caller's transaction."""
    primary_key = (
        "INTEGER PRIMARY KEY AUTOINCREMENT" if isinstance(conn, _SQLiteConnection)
        else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    )
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS users (
            id {primary_key},
            name TEXT NOT NULL,
            email TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            role TEXT NOT NULL CHECK (role IN ('pm', 'employee')),
            created_at TEXT NOT NULL
        )
    """)
    user_columns = _column_names(conn, "users")
    if "google_sub" not in user_columns:
        conn.execute("ALTER TABLE users ADD COLUMN google_sub TEXT")
    for column, definition in (
        ("job_title", "TEXT NOT NULL DEFAULT ''"),
        ("department", "TEXT NOT NULL DEFAULT ''"),
        ("google_email", "TEXT"),
        ("session_version", "INTEGER NOT NULL DEFAULT 0"),
        ("deleted_at", "TEXT"),
    ):
        if column not in user_columns:
            conn.execute(f"ALTER TABLE users ADD COLUMN {column} {definition}")
    conn.execute("UPDATE users SET google_email=email WHERE google_sub IS NOT NULL AND google_email IS NULL")
    conn.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_users_google_sub ON users(google_sub)")
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS projects (
            id {primary_key},
            name TEXT NOT NULL,
            description TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY (created_by) REFERENCES users(id)
        )
    """)
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS project_members (
            project_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            PRIMARY KEY (project_id, user_id),
            FOREIGN KEY (project_id) REFERENCES projects(id),
            FOREIGN KEY (user_id) REFERENCES users(id)
        )
    """)
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS meetings (
            id {primary_key},
            title TEXT NOT NULL,
            transcript TEXT,
            summary TEXT,
            project_id INTEGER,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY (created_by) REFERENCES users(id),
            FOREIGN KEY (project_id) REFERENCES projects(id)
        )
    """)
    meeting_columns = _column_names(conn, "meetings")
    for column, definition in (
        ("recording_storage_path", "TEXT"),
        ("recording_filename", "TEXT"),
        ("recording_mime_type", "TEXT"),
        ("recording_file_size", "INTEGER"),
        ("recording_duration", "REAL"),
        ("meeting_minutes", "TEXT"),
    ):
        if column not in meeting_columns:
            conn.execute(f"ALTER TABLE meetings ADD COLUMN {column} {definition}")
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS decisions (
            id {primary_key},
            meeting_id INTEGER NOT NULL,
            decision TEXT NOT NULL,
            FOREIGN KEY (meeting_id) REFERENCES meetings(id)
        )
    """)
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS questions (
            id {primary_key},
            meeting_id INTEGER NOT NULL,
            question TEXT NOT NULL,
            FOREIGN KEY (meeting_id) REFERENCES meetings(id)
        )
    """)
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS action_items (
            id {primary_key},
            meeting_id INTEGER NOT NULL,
            task TEXT NOT NULL,
            owner_name TEXT,
            owner_user_id INTEGER,
            deadline TEXT,
            priority TEXT,
            evidence TEXT,
            status TEXT NOT NULL DEFAULT 'Pending',
            approved INTEGER NOT NULL DEFAULT 0,
            FOREIGN KEY (meeting_id) REFERENCES meetings(id),
            FOREIGN KEY (owner_user_id) REFERENCES users(id)
        )
    """)
    conn.execute(f"""
        CREATE TABLE IF NOT EXISTS followups (
            id {primary_key},
            action_item_id INTEGER NOT NULL,
            created_by INTEGER,
            recipient_user_id INTEGER,
            followup_type TEXT NOT NULL,
            message TEXT NOT NULL,
            created_at TEXT NOT NULL,
            sent_at TEXT,
            status TEXT NOT NULL DEFAULT 'Draft',
            employee_response TEXT,
            responded_at TEXT,
            FOREIGN KEY (action_item_id) REFERENCES action_items(id)
        )
    """)
    columns = _column_names(conn, "followups")
    for name, definition in (
        ("created_by", "INTEGER"),
        ("recipient_user_id", "INTEGER"),
        ("employee_response", "TEXT"),
        ("responded_at", "TEXT"),
    ):
        if name not in columns:
            conn.execute(f"ALTER TABLE followups ADD COLUMN {name} {definition}")
    conn.execute("CREATE INDEX IF NOT EXISTS idx_followups_recipient ON followups(recipient_user_id)")
    # Older follow-ups predate recipient/creator tracking. Adding the columns
    # alone leaves sent messages invisible to their employees' inboxes.
    # Fill only missing links so existing recipients and replies stay intact.
    conn.execute("""
        UPDATE followups
        SET recipient_user_id = (
            SELECT owner_user_id FROM action_items
            WHERE action_items.id = followups.action_item_id
        )
        WHERE recipient_user_id IS NULL
    """)
    conn.execute("""
        UPDATE followups
        SET created_by = (
            SELECT meetings.created_by FROM action_items
            JOIN meetings ON meetings.id = action_items.meeting_id
            WHERE action_items.id = followups.action_item_id
        )
        WHERE created_by IS NULL
    """)


# ---------------- users ----------------

def create_user(name: str, email: str, password_hash: str, role: str) -> int:
    with get_conn() as conn:
        cur = conn.execute(
            "INSERT INTO users (name, email, password_hash, role, created_at) VALUES (%s, %s, %s, %s, %s) RETURNING id",
            (name, email, password_hash, role, datetime.now().isoformat()),
        )
        return cur.fetchone()["id"]


def get_user_by_email(email: str):
    with get_conn() as conn:
        return conn.execute("SELECT * FROM users WHERE email=%s AND deleted_at IS NULL", (email,)).fetchone()


def get_user_by_id(user_id: int):
    with get_conn() as conn:
        return conn.execute("SELECT * FROM users WHERE id=%s AND deleted_at IS NULL", (user_id,)).fetchone()


def get_user_by_google_sub(subject: str):
    with get_conn() as conn:
        return conn.execute("SELECT * FROM users WHERE google_sub=%s AND deleted_at IS NULL", (subject,)).fetchone()


def get_users_by_email_case_insensitive(email: str):
    with get_conn() as conn:
        return conn.execute("SELECT * FROM users WHERE lower(email)=lower(%s) AND deleted_at IS NULL", (email,)).fetchall()


def create_google_user(name: str, email: str, subject: str, role: str):
    with get_conn() as conn:
        _lock_user_writes(conn)
        if conn.execute("SELECT 1 FROM users WHERE lower(email)=lower(%s)", (email,)).fetchone():
            raise sqlite3.IntegrityError("Account already exists")
        cur = conn.execute(
            """INSERT INTO users (name, email, password_hash, role, created_at, google_sub, google_email)
               VALUES (%s, %s, '', %s, %s, %s, %s) RETURNING id""",
            (name, email, role, datetime.now().isoformat(), subject, email),
        )
        return conn.execute("SELECT * FROM users WHERE id=%s", (cur.fetchone()["id"],)).fetchone()


def link_google_account(user_id: int, subject: str, google_email=None, expected_version=None):
    with get_conn() as conn:
        result = conn.execute(
            """UPDATE users SET google_sub=%s, google_email=COALESCE(%s, email), session_version=session_version+1
               WHERE id=%s AND google_sub IS NULL AND deleted_at IS NULL
               AND (CAST(%s AS INTEGER) IS NULL OR session_version=%s)""",
            (subject, google_email, user_id, expected_version, expected_version),
        )
        if result.rowcount != 1:
            raise sqlite3.IntegrityError("Google account already linked")


def update_user_profile(user_id: int, name: str, email: str, job_title: str, department: str, expected_version: int):
    with get_conn() as conn:
        _lock_user_writes(conn)
        if conn.execute(
            "SELECT 1 FROM users WHERE lower(email)=lower(%s) AND id != %s", (email, user_id),
        ).fetchone():
            raise sqlite3.IntegrityError("Email already in use")
        result = conn.execute(
            """UPDATE users SET name=%s, job_title=%s, department=%s,
               session_version=session_version + CASE WHEN email != %s THEN 1 ELSE 0 END, email=%s
               WHERE id=%s AND session_version=%s AND deleted_at IS NULL""",
            (name, job_title, department, email, email, user_id, expected_version),
        )
        if result.rowcount != 1:
            raise ValueError("Your account changed. Refresh and try again.")
        return conn.execute("SELECT * FROM users WHERE id=%s", (user_id,)).fetchone()


def get_user_team_details(user_id: int, role: str):
    with get_conn() as conn:
        if role == "pm":
            teams = conn.execute("SELECT id, name FROM projects WHERE created_by=%s ORDER BY name", (user_id,)).fetchall()
            count = conn.execute(
                """SELECT COUNT(DISTINCT u.id) AS count FROM project_members m
                   JOIN projects p ON p.id=m.project_id JOIN users u ON u.id=m.user_id
                   WHERE p.created_by=%s AND u.role='employee' AND u.deleted_at IS NULL""", (user_id,),
            ).fetchone()["count"]
            managers = []
        else:
            teams = conn.execute(
                """SELECT p.id, p.name FROM projects p JOIN project_members m ON m.project_id=p.id
                   WHERE m.user_id=%s ORDER BY p.name""", (user_id,),
            ).fetchall()
            managers = conn.execute(
                """SELECT DISTINCT u.id, u.name FROM users u JOIN projects p ON p.created_by=u.id
                   JOIN project_members m ON m.project_id=p.id
                   WHERE m.user_id=%s AND u.role='pm' AND u.deleted_at IS NULL ORDER BY u.name""", (user_id,),
            ).fetchall()
            count = None
        return {"project_teams": [dict(row) for row in teams], "team_member_count": count,
                "reporting_managers": [dict(row) for row in managers]}


def set_user_password(user_id: int, password_hash: str, expected_version: int):
    with get_conn() as conn:
        result = conn.execute(
            """UPDATE users SET password_hash=%s, session_version=session_version+1
               WHERE id=%s AND session_version=%s AND deleted_at IS NULL""", (password_hash, user_id, expected_version),
        )
        if result.rowcount != 1:
            raise ValueError("Your account changed. Refresh and try again.")


def unlink_google_account(user_id: int, expected_version: int):
    with get_conn() as conn:
        result = conn.execute(
            """UPDATE users SET google_sub=NULL, google_email=NULL, session_version=session_version+1
               WHERE id=%s AND session_version=%s AND password_hash != '' AND google_sub IS NOT NULL AND deleted_at IS NULL""",
            (user_id, expected_version),
        )
        if result.rowcount != 1:
            raise ValueError("Set a password before unlinking Google, or refresh your account and try again.")


def revoke_user_sessions(user_id: int):
    with get_conn() as conn:
        conn.execute("UPDATE users SET session_version=session_version+1 WHERE id=%s AND deleted_at IS NULL", (user_id,))


def delete_user_account(user_id: int, expected_version: int):
    """Remove the login/profile while retaining an anonymous author for shared work."""
    with get_conn() as conn:
        result = conn.execute(
            """UPDATE users SET name='Deleted account', email=%s, password_hash='', google_sub=NULL,
               google_email=NULL, job_title='', department='', deleted_at=%s, session_version=session_version+1
               WHERE id=%s AND session_version=%s AND deleted_at IS NULL""",
            (f"deleted-{user_id}-{uuid4().hex}@account.invalid", datetime.now().isoformat(), user_id, expected_version),
        )
        if result.rowcount != 1:
            raise ValueError("Your account changed. Refresh and try again.")
        conn.execute("DELETE FROM project_members WHERE user_id=%s", (user_id,))
        conn.execute("UPDATE action_items SET owner_user_id=NULL, owner_name='Former team member' WHERE owner_user_id=%s", (user_id,))


def list_employees():
    with get_conn() as conn:
        return conn.execute("SELECT id, name, email FROM users WHERE role='employee' AND deleted_at IS NULL").fetchall()


# ---------------- projects ----------------

def create_project(name: str, description: str, created_by: int) -> int:
    with get_conn() as conn:
        cur = conn.execute(
            "INSERT INTO projects (name, description, created_by, created_at) VALUES (%s, %s, %s, %s) RETURNING id",
            (name, description, created_by, datetime.now().isoformat()),
        )
        return cur.fetchone()["id"]


def get_projects():
    with get_conn() as conn:
        return conn.execute("SELECT * FROM projects ORDER BY created_at DESC").fetchall()


def get_project(project_id: int):
    with get_conn() as conn:
        return conn.execute("SELECT * FROM projects WHERE id=%s", (project_id,)).fetchone()


def delete_project(project_id: int) -> bool:
    """Delete a project while preserving its historical meeting records."""
    with get_conn() as conn:
        conn.execute("UPDATE meetings SET project_id=NULL WHERE project_id=%s", (project_id,))
        conn.execute("DELETE FROM project_members WHERE project_id=%s", (project_id,))
        result = conn.execute("DELETE FROM projects WHERE id=%s", (project_id,))
        return result.rowcount > 0


def add_project_member(project_id: int, user_id: int):
    with get_conn() as conn:
        conn.execute(
            "INSERT INTO project_members (project_id, user_id) VALUES (%s, %s) ON CONFLICT (project_id, user_id) DO NOTHING",
            (project_id, user_id),
        )


def remove_project_member(project_id: int, user_id: int):
    with get_conn() as conn:
        conn.execute(
            "DELETE FROM project_members WHERE project_id=%s AND user_id=%s", (project_id, user_id)
        )


def get_project_members(project_id: int):
    with get_conn() as conn:
        return conn.execute(
            """SELECT users.id, users.name, users.email FROM users
               JOIN project_members ON users.id = project_members.user_id
               WHERE project_members.project_id=%s""",
            (project_id,),
        ).fetchall()


def get_user_projects(user_id: int):
    """Projects a given user (employee) is a member of."""
    with get_conn() as conn:
        return conn.execute(
            """SELECT projects.* FROM projects
               JOIN project_members ON projects.id = project_members.project_id
               WHERE project_members.user_id=%s
               ORDER BY projects.created_at DESC""",
            (user_id,),
        ).fetchall()


def is_project_member(project_id: int, user_id: int) -> bool:
    with get_conn() as conn:
        row = conn.execute(
            "SELECT 1 FROM project_members WHERE project_id=%s AND user_id=%s", (project_id, user_id)
        ).fetchone()
        return row is not None


# ---------------- meetings ----------------

def add_meeting(title: str, transcript: str, summary: str, created_by: int, project_id: int = None, recording=None, meeting_minutes: str = None) -> int:
    with get_conn() as conn:
        cur = conn.execute(
            """INSERT INTO meetings
               (title, transcript, summary, project_id, created_by, created_at,
                recording_storage_path, recording_filename, recording_mime_type,
                recording_file_size, recording_duration, meeting_minutes)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING id""",
            (title, transcript, summary, project_id, created_by, datetime.now().isoformat(),
             recording.get("storage_path") if recording else None,
             recording.get("filename") if recording else None,
             recording.get("mime_type") if recording else None,
             recording.get("file_size") if recording else None,
             recording.get("duration") if recording else None, meeting_minutes),
        )
        return cur.fetchone()["id"]


def add_decision(meeting_id: int, decision: str):
    with get_conn() as conn:
        conn.execute("INSERT INTO decisions (meeting_id, decision) VALUES (%s, %s)", (meeting_id, decision))


def add_question(meeting_id: int, question: str):
    with get_conn() as conn:
        conn.execute("INSERT INTO questions (meeting_id, question) VALUES (%s, %s)", (meeting_id, question))


def get_meetings(user_id=None, role=None):
    with get_conn() as conn:
        if role == "pm" or user_id is None:
            return conn.execute("SELECT * FROM meetings ORDER BY created_at DESC").fetchall()
        return conn.execute(
            """SELECT meetings.* FROM meetings
               WHERE meetings.created_by=%s OR EXISTS (
                 SELECT 1 FROM project_members
                 WHERE project_members.project_id=meetings.project_id
                   AND project_members.user_id=%s
               ) ORDER BY meetings.created_at DESC""",
            (user_id, user_id),
        ).fetchall()


def get_meeting(meeting_id: int):
    with get_conn() as conn:
        return conn.execute("SELECT * FROM meetings WHERE id=%s", (meeting_id,)).fetchone()


def edit_meeting(meeting_id, data):
    with get_conn() as conn:
        meeting = conn.execute("SELECT transcript, meeting_minutes FROM meetings WHERE id=%s", (meeting_id,)).fetchone()
        if meeting["meeting_minutes"]:
            if data.transcript != meeting["transcript"]:
                raise ValueError("The transcript for generated meeting minutes cannot be edited without reanalysis")
            minutes = data.meeting_minutes.model_dump() if data.meeting_minutes else json.loads(meeting["meeting_minutes"])
            if data.meeting_minutes:
                for section in ("action_items", "dependencies_blockers_issues", "milestones"):
                    for number, item in enumerate(minutes[section], start=1):
                        item["ref_no"] = number
            else:
                minutes["meeting_summary"] = data.summary
            conn.execute("UPDATE meetings SET title=%s, summary=%s, meeting_minutes=%s WHERE id=%s",
                         (data.title, minutes["meeting_summary"], json.dumps(minutes, ensure_ascii=False), meeting_id))
        else:
            conn.execute("UPDATE meetings SET title=%s, summary=%s, transcript=%s WHERE id=%s",
                         (data.title, data.summary, data.transcript, meeting_id))
        conn.execute("DELETE FROM decisions WHERE meeting_id=%s", (meeting_id,))
        conn.execute("DELETE FROM questions WHERE meeting_id=%s", (meeting_id,))
        for value in data.decisions:
            if value.strip():
                conn.execute("INSERT INTO decisions (meeting_id, decision) VALUES (%s, %s)", (meeting_id, value.strip()))
        for value in data.questions:
            if value.strip():
                conn.execute("INSERT INTO questions (meeting_id, question) VALUES (%s, %s)", (meeting_id, value.strip()))


def delete_meeting(meeting_id, remove_recording):
    with get_conn() as conn:
        # Lock the meeting until its dependents and recording have been removed.
        if isinstance(conn, _SQLiteConnection):
            conn.execute("BEGIN IMMEDIATE")
            meeting = conn.execute("SELECT * FROM meetings WHERE id=%s", (meeting_id,)).fetchone()
        else:
            meeting = conn.execute("SELECT * FROM meetings WHERE id=%s FOR UPDATE", (meeting_id,)).fetchone()
        if not meeting:
            return
        conn.execute("DELETE FROM followups WHERE action_item_id IN (SELECT id FROM action_items WHERE meeting_id=%s)", (meeting_id,))
        for table in ("action_items", "decisions", "questions"):
            conn.execute(f"DELETE FROM {table} WHERE meeting_id=%s", (meeting_id,))
        conn.execute("DELETE FROM meetings WHERE id=%s", (meeting_id,))
        if meeting["recording_storage_path"]:
            remove_recording(meeting["recording_storage_path"])


def can_view_meeting(meeting, user) -> bool:
    return user["role"] == "pm" or meeting["created_by"] == user["id"] or (
        meeting["project_id"] is not None and is_project_member(meeting["project_id"], user["id"])
    )


def get_decisions(meeting_id: int):
    with get_conn() as conn:
        return conn.execute("SELECT * FROM decisions WHERE meeting_id=%s", (meeting_id,)).fetchall()


def get_questions(meeting_id: int):
    with get_conn() as conn:
        return conn.execute("SELECT * FROM questions WHERE meeting_id=%s", (meeting_id,)).fetchall()


# ---------------- action items ----------------

def add_action_item(meeting_id, task, owner_name, deadline, priority, evidence, owner_user_id=None) -> int:
    with get_conn() as conn:
        cur = conn.execute(
            """INSERT INTO action_items
               (meeting_id, task, owner_name, owner_user_id, deadline, priority, evidence, status, approved)
               VALUES (%s, %s, %s, %s, %s, %s, %s, 'Pending', 0) RETURNING id""",
            (meeting_id, task, owner_name, owner_user_id, deadline, priority, evidence),
        )
        return cur.fetchone()["id"]


def edit_action_item(item_id, task, owner_name, deadline, priority, owner_user_id=None):
    with get_conn() as conn:
        conn.execute(
            "UPDATE action_items SET task=%s, owner_name=%s, owner_user_id=%s, deadline=%s, priority=%s WHERE id=%s",
            (task, owner_name, owner_user_id, deadline, priority, item_id),
        )


def approve_action_item(item_id: int):
    with get_conn() as conn:
        conn.execute("UPDATE action_items SET approved=1 WHERE id=%s", (item_id,))


def update_status(item_id: int, status: str):
    with get_conn() as conn:
        conn.execute("UPDATE action_items SET status=%s WHERE id=%s", (status, item_id))


def get_action_item(item_id: int):
    with get_conn() as conn:
        return conn.execute("SELECT * FROM action_items WHERE id=%s", (item_id,)).fetchone()


def get_action_items(meeting_id: int = None, approved_only: bool = False, owner_user_id: int = None):
    query = """
        SELECT action_items.*, meetings.title AS meeting_title, meetings.project_id AS project_id,
                             projects.name AS project_name,
                             (SELECT employee_response FROM followups
                                WHERE followups.action_item_id = action_items.id
                                    AND employee_response IS NOT NULL
                                ORDER BY responded_at DESC LIMIT 1) AS employee_response,
                             (SELECT responded_at FROM followups
                                WHERE followups.action_item_id = action_items.id
                                    AND employee_response IS NOT NULL
                                ORDER BY responded_at DESC LIMIT 1) AS employee_responded_at
        FROM action_items
        LEFT JOIN meetings ON action_items.meeting_id = meetings.id
        LEFT JOIN projects ON meetings.project_id = projects.id
    """
    conditions, params = [], []
    if meeting_id is not None:
        conditions.append("action_items.meeting_id=%s")
        params.append(meeting_id)
    if approved_only:
        conditions.append("action_items.approved=1")
    if owner_user_id is not None:
        conditions.append("action_items.owner_user_id=%s")
        params.append(owner_user_id)
    if conditions:
        query += " WHERE " + " AND ".join(conditions)
    query += """ ORDER BY
        CASE action_items.priority WHEN 'High' THEN 0 WHEN 'Medium' THEN 1 ELSE 2 END,
        action_items.deadline"""
    with get_conn() as conn:
        return conn.execute(query, params).fetchall()


def get_overdue_items():
    today = date.today().isoformat()
    with get_conn() as conn:
        rows = conn.execute(
            "SELECT * FROM action_items WHERE approved=1 AND status != 'Completed'"
        ).fetchall()
    overdue = []
    for row in rows:
        try:
            d = datetime.fromisoformat(row["deadline"]).date().isoformat()
            if d < today:
                overdue.append(row)
        except (ValueError, TypeError):
            continue
    return overdue


def classify_action_item(item):
    """Classify an action item using stored deadline/status data only."""
    status = item["status"] or "Pending"
    if status == "Completed":
        return "Completed"

    if status.lower() == "at risk":
        return "At Risk"

    try:
        deadline = date.fromisoformat(item["deadline"])
    except (TypeError, ValueError):
        return None

    days_until_due = (deadline - date.today()).days
    if days_until_due < 0:
        return "Overdue"
    if days_until_due <= 3:
        return "Due Soon"
    return None


def get_followups(action_item_id: int):
    with get_conn() as conn:
        return conn.execute(
            "SELECT * FROM followups WHERE action_item_id=%s ORDER BY created_at DESC",
            (action_item_id,),
        ).fetchall()


def add_followup(action_item_id: int, followup_type: str, message: str, created_by: int, recipient_user_id: int) -> int:
    with get_conn() as conn:
        cur = conn.execute(
            """INSERT INTO followups
               (action_item_id, created_by, recipient_user_id, followup_type, message, created_at, status)
               VALUES (%s, %s, %s, %s, %s, %s, 'Draft') RETURNING id""",
            (action_item_id, created_by, recipient_user_id, followup_type, message, datetime.now().isoformat()),
        )
        return cur.fetchone()["id"]


def get_followup(followup_id: int):
    with get_conn() as conn:
        return conn.execute("SELECT * FROM followups WHERE id=%s", (followup_id,)).fetchone()


def mark_followup_sent(followup_id: int):
    with get_conn() as conn:
        conn.execute(
            "UPDATE followups SET status='Sent', sent_at=%s WHERE id=%s",
            (datetime.now().isoformat(), followup_id),
        )


def update_followup_message(followup_id: int, message: str):
    with get_conn() as conn:
        conn.execute(
            "UPDATE followups SET message=%s WHERE id=%s AND status='Draft'",
            (message, followup_id),
        )


def get_received_followups(user_id: int):
    with get_conn() as conn:
        return conn.execute(
            """SELECT followups.*, action_items.task, action_items.deadline,
                      action_items.priority, action_items.status AS action_status,
                      meetings.title AS meeting_title,
                      creator.name AS project_manager_name
               FROM followups
               JOIN action_items ON action_items.id = followups.action_item_id
               LEFT JOIN meetings ON meetings.id = action_items.meeting_id
               LEFT JOIN users AS creator ON creator.id = followups.created_by
               WHERE followups.recipient_user_id=%s AND followups.status='Sent'
               ORDER BY followups.sent_at DESC""",
            (user_id,),
        ).fetchall()


def add_employee_response(followup_id: int, response: str):
    with get_conn() as conn:
        conn.execute(
            "UPDATE followups SET employee_response=%s, responded_at=%s WHERE id=%s AND status='Sent'",
            (response, datetime.now().isoformat(), followup_id),
        )
